import test from 'node:test';
import assert from 'node:assert/strict';
import {createMutationDispatcher} from '../cloud-blog-dispatcher.mjs';
import {transition} from '../cloud-blog-lease.mjs';
import {planIssue} from '../cloud-blog-execution-plan.mjs';
const SHA='a'.repeat(40), NOW='2026-10-09T01:10:00Z', identity={owner:'worker',epoch:1};
function fixture(){
 let now=NOW, serial=1, state=transition({schema:1,epoch:0,status:'idle',owner:null,until:null,pending:null},{action:'acquire',owner:'worker',ttl_seconds:60},now);
 const calls=[], outcomes=new Map();
 const plan=()=>({target_sha:SHA,plan:{status:'PLAN_ONLY',external_mutations:false,evidence_mode:'MOCK',run_id:'run-1',observed_at:now,phase:'RELEASE',intents:[{kind:'DEPLOY_VERIFIED_VERSION',target_sha:SHA,version_id:'v2',rollback_version_id:'v1'}]}});
 const ports={clock:()=>now,prepare:async()=>plan(),authorize:async op=>({authorized:true,...op,expires_at:new Date(Date.parse(now)+60000).toISOString()}),
  reconcile:async op=>({complete:true,operation_id:op.operation_id,kind:op.kind,target_sha:op.target_sha,observed_at:now,state:outcomes.has(op.operation_id)?'APPLIED':'ABSENT',matches:outcomes.has(op.operation_id)?1:0,result_id:outcomes.get(op.operation_id)}),
  invoke:async op=>{calls.push(op);outcomes.set(op.operation_id,'deployment-2');},
  lease:{read:async()=>({state:structuredClone(state),sha:String(serial)}),change:async(command,at)=>{state=transition(state,command,at);serial++;return {status:'CONFIRMED',sha:String(serial),owner:state.owner,epoch:state.epoch,pending:state.pending};},
   assertOperation:async(fence,id,at)=>{assert.equal(fence.sha,String(serial),'STALE_FENCE');assert.equal(state.pending?.id,id);assert.ok(Date.parse(at)<Date.parse(state.until),'EXPIRED');return {sha:String(serial),state:structuredClone(state)};}}
 };
 return {ports,calls,outcomes,plan,get state(){return state;},setTime:t=>{now=t;},changeState:s=>{state=s;},race:()=>{serial++;}};
}
test('default disabled performs no authorization, journal, reconcile or invoke',async()=>{const m=fixture();for(const k of ['authorize','reconcile','invoke'])m.ports[k]=()=>{throw Error('must not call');};m.ports.lease=null;assert.equal((await createMutationDispatcher(m.ports).dispatch({})).status,'DISABLED_PLAN_ONLY');});
test('one journaled call, authoritative readback, then durable resolution',async()=>{const m=fixture();const r=await createMutationDispatcher(m.ports,{execute:true}).dispatch({},identity);assert.equal(r.status,'APPLIED_VERIFIED');assert.equal(m.calls.length,1);assert.equal(m.state.pending,null);assert.ok(Object.isFrozen(m.calls[0].intent));});
test('lost successful response reconciles without retry',async()=>{const m=fixture(), invoke=m.ports.invoke;m.ports.invoke=async op=>{await invoke(op);throw Error('lost');};assert.equal((await createMutationDispatcher(m.ports,{execute:true}).dispatch({},identity)).status,'APPLIED_VERIFIED');assert.equal(m.calls.length,1);});
test('unknown outcome survives a fresh dispatcher and never invokes again',async()=>{const m=fixture();m.ports.invoke=async op=>{m.calls.push(op);throw Error('lost');};assert.equal((await createMutationDispatcher(m.ports,{execute:true}).dispatch({},identity)).status,'UNRESOLVED_STOP');assert.ok(m.state.pending);assert.equal((await createMutationDispatcher(m.ports,{execute:true}).dispatch({},identity)).status,'UNRESOLVED_STOP');assert.equal(m.calls.length,1);});
test('restart can resolve uniquely applied remote result after lease expiry',async()=>{const m=fixture();m.ports.invoke=async op=>{m.calls.push(op);};await createMutationDispatcher(m.ports,{execute:true}).dispatch({},identity);m.outcomes.set(m.calls[0].operation_id,'late-deployment');m.setTime('2026-10-09T01:12:00Z');assert.equal((await createMutationDispatcher(m.ports,{execute:true}).dispatch({},identity)).status,'APPLIED_VERIFIED');assert.equal(m.calls.length,1);});
test('resolved operation is not repeated with same run and intent',async()=>{const m=fixture(), d=createMutationDispatcher(m.ports,{execute:true});await d.dispatch({},identity);assert.equal((await d.dispatch({},identity)).status,'ALREADY_APPLIED');assert.equal(m.calls.length,1);});
for(const mutation of ['complete','target','id','stale','ambiguous','unknown'])test(`bad preflight ${mutation} cannot write`,async()=>{const m=fixture(),read=m.ports.reconcile;m.ports.reconcile=async op=>{const r=await read(op);if(mutation==='complete')r.complete=false;if(mutation==='target')r.target_sha='b'.repeat(40);if(mutation==='id')r.operation_id='wrong';if(mutation==='stale')r.observed_at='2026-10-09T00:00:00Z';if(mutation==='ambiguous'){r.state='APPLIED';r.matches=2;r.result_id='x';}if(mutation==='unknown')r.state='UNKNOWN';return r;};await assert.rejects(createMutationDispatcher(m.ports,{execute:true}).dispatch({},identity));assert.equal(m.calls.length,0);assert.equal(m.state.pending,null);});
test('wrong owner or epoch cannot write',async()=>{for(const id of [{owner:'other',epoch:1},{owner:'worker',epoch:2}]){const m=fixture();await assert.rejects(createMutationDispatcher(m.ports,{execute:true}).dispatch({},id),/STALE_OWNER/);assert.equal(m.calls.length,0);}});
test('expiry blocks new mutation',async()=>{const m=fixture();m.setTime('2026-10-09T01:12:00Z');await assert.rejects(createMutationDispatcher(m.ports,{execute:true}).dispatch({},identity),/PORT_FAILED/);assert.equal(m.calls.length,0);});
test('authorization denied before journal',async()=>{const m=fixture();m.ports.authorize=async()=>({authorized:false});await assert.rejects(createMutationDispatcher(m.ports,{execute:true}).dispatch({},identity),/authorization/);assert.equal(m.state.pending,null);});
test('approval revocation after journal leaves pending and never invokes',async()=>{const m=fixture();let n=0;const yes=m.ports.authorize;m.ports.authorize=async op=>++n===1?yes(op):{authorized:false};await assert.rejects(createMutationDispatcher(m.ports,{execute:true}).dispatch({},identity),/Authorization changed/);assert.ok(m.state.pending);assert.equal(m.calls.length,0);});
test('plan change after journal leaves pending and never invokes',async()=>{const m=fixture();let n=0;m.ports.prepare=async()=>{const p=m.plan();if(++n>1)p.plan.intents[0].version_id='changed';return p;};await assert.rejects(createMutationDispatcher(m.ports,{execute:true}).dispatch({},identity),/PLAN_CHANGED/);assert.equal(m.calls.length,0);assert.ok(m.state.pending);});
test('unconfirmed journal cannot dispatch',async()=>{const m=fixture();m.ports.lease.change=async()=>({status:'CAS_NOT_CONFIRMED_STOP'});await assert.rejects(createMutationDispatcher(m.ports,{execute:true}).dispatch({},identity),/JOURNAL/);assert.equal(m.calls.length,0);});
test('fence change after final authorization cannot dispatch',async()=>{const m=fixture();let n=0;const yes=m.ports.authorize;m.ports.authorize=async op=>{if(++n===2)m.race();return yes(op);};await assert.rejects(createMutationDispatcher(m.ports,{execute:true}).dispatch({},identity),/PORT_FAILED/);assert.equal(m.calls.length,0);});
test('unknown readback remains journaled even after successful response',async()=>{const m=fixture();let n=0;const read=m.ports.reconcile;m.ports.reconcile=async op=>{if(++n>1)throw Error('unavailable');return read(op);};assert.equal((await createMutationDispatcher(m.ports,{execute:true}).dispatch({},identity)).status,'UNRESOLVED_STOP');assert.ok(m.state.pending);});
test('different pending operation blocks without reconciliation or invoke',async()=>{const m=fixture();m.changeState({...m.state,pending:{id:'other',kind:'deploy',target_sha:SHA}});await assert.rejects(createMutationDispatcher(m.ports,{execute:true}).dispatch({},identity),/DIFFERENT_PENDING/);assert.equal(m.calls.length,0);});
test('concurrent call on one dispatcher rejected',async()=>{const m=fixture();let unblock;m.ports.prepare=()=>new Promise(r=>{unblock=()=>r(m.plan());});const d=createMutationDispatcher(m.ports), first=d.dispatch({});await assert.rejects(d.dispatch({}),/LOCAL_OPERATION/);unblock();await first;});
test('MOCK plan cannot execute as trusted provenance',async()=>{const m=fixture();await assert.rejects(createMutationDispatcher(m.ports,{execute:true,mode:'TRUSTED_ADAPTER'}).dispatch({},identity),/provenance/);assert.equal(m.calls.length,0);});
test('unknown, prototype and local-only intents fail closed',async()=>{for(const kind of ['constructor','toString','__proto__','RUN_COMPLETE_LOCAL_RELEASE_QA','invented']){const m=fixture();m.ports.prepare=async()=>{const p=m.plan();p.plan.intents[0].kind=kind;return p;};await assert.rejects(createMutationDispatcher(m.ports,{execute:true}).dispatch({},identity),/supported/);}});
test('required intent target cannot be absent/null/empty',async()=>{for(const value of [undefined,null,'']){const m=fixture();m.ports.prepare=async()=>{const p=m.plan();p.plan.intents[0].target_sha=value;return p;};await assert.rejects(createMutationDispatcher(m.ports,{execute:true}).dispatch({},identity),/target/);assert.equal(m.calls.length,0);}});
test('multiple operations cannot be batched through one journal',async()=>{const m=fixture();m.ports.prepare=async()=>{const p=m.plan();p.plan.intents.push({...p.plan.intents[0]});return p;};await assert.rejects(createMutationDispatcher(m.ports,{execute:true}).dispatch({},identity),/supported/);});
test('Ready is a separate journaled operation requiring exact approval',async()=>{const m=fixture();m.ports.prepare=async()=>{const p=m.plan();p.plan.intents=[{kind:'MARK_READY_FOR_REVIEW',pr_number:10,expected_head_sha:SHA}];return p;};assert.equal((await createMutationDispatcher(m.ports,{execute:true}).dispatch({},identity)).status,'APPLIED_VERIFIED');assert.equal(m.calls[0].kind,'pr_ready');});
test('new source_push kind round trips through existing lease schema',async()=>{const m=fixture();m.ports.prepare=async()=>{const p=m.plan();p.plan.intents=[{kind:'PUSH_EXACT_MAIN_SOURCE',target_sha:SHA}];return p;};assert.equal((await createMutationDispatcher(m.ports,{execute:true}).dispatch({},identity)).status,'APPLIED_VERIFIED');assert.equal(m.calls[0].kind,'source_push');});
test('explicit restart recovery needs no obsolete mutation plan or payload',async()=>{const m=fixture(),read=m.ports.reconcile;let count=0;m.ports.reconcile=async op=>{if(++count===2)throw Error('lost read');return read(op);};await createMutationDispatcher(m.ports,{execute:true}).dispatch({},identity);assert.ok(m.state.pending);m.ports.prepare=()=>{throw Error('already applied, current plan is NOOP');};m.ports.authorize=()=>{throw Error('not needed for read reconciliation');};assert.equal((await createMutationDispatcher(m.ports,{execute:true}).recoverPending(identity)).status,'APPLIED_VERIFIED');assert.equal(m.calls.length,1);assert.equal(m.state.pending,null);});
test('default recovery never resolves or invokes',async()=>{const m=fixture();m.ports.invoke=async op=>{m.calls.push(op);};await createMutationDispatcher(m.ports,{execute:true}).dispatch({},identity);m.ports.lease.change=()=>{throw Error('no write');};assert.equal((await createMutationDispatcher(m.ports).recoverPending(identity)).status,'DISABLED_RECOVERY_ONLY');assert.ok(m.state.pending);});
test('slow final fence read cannot cross lease expiry',async()=>{const m=fixture(),read=m.ports.lease.assertOperation;let n=0;m.ports.lease.assertOperation=async(...a)=>{const r=await read(...a);if(++n===2)m.setTime('2026-10-09T01:11:00Z');return r;};await assert.rejects(createMutationDispatcher(m.ports,{execute:true}).dispatch({},identity),/(?:LEASE|AUTHORIZATION)_EXPIRED_BEFORE/);assert.equal(m.calls.length,0);assert.ok(m.state.pending);});
test('slow authorization cannot dispatch stale plan even with long lease',async()=>{const m=fixture();m.changeState({...m.state,until:'2026-10-09T01:25:00Z'});const auth=m.ports.authorize;let n=0;m.ports.authorize=async op=>{if(++n===2)m.setTime('2026-10-09T01:12:00Z');return auth(op);};await assert.rejects(createMutationDispatcher(m.ports,{execute:true}).dispatch({},identity),/PLAN_EXPIRED_BEFORE/);assert.equal(m.calls.length,0);});
test('provider errors never expose private messages or stack causes',async()=>{const m=fixture();m.ports.prepare=async()=>{throw new Error('SECRET_TOKEN');};await assert.rejects(createMutationDispatcher(m.ports,{execute:true}).dispatch({},identity),e=>{assert.match(e.message,/PORT_FAILED/);assert.ok(!e.stack.includes('SECRET_TOKEN'));assert.equal(e.cause,undefined);return true;});});
test('final fence cannot cross expiry of inherited authorization evidence',async()=>{const m=fixture(),auth=m.ports.authorize,read=m.ports.lease.assertOperation;m.ports.authorize=async op=>({...await auth(op),expires_at:'2026-10-09T01:10:01Z'});let n=0;m.ports.lease.assertOperation=async(...a)=>{const r=await read(...a);if(++n===2)m.setTime('2026-10-09T01:10:02Z');return r;};await assert.rejects(createMutationDispatcher(m.ports,{execute:true}).dispatch({},identity),/AUTHORIZATION_EXPIRED_BEFORE/);assert.equal(m.calls.length,0);});
test('real Issue planner becomes reuse after lost readback; recovery still resolves',async()=>{const m=fixture();let created=false,reads=0;const read=m.ports.reconcile,invoke=m.ports.invoke;m.ports.prepare=async()=>({target_sha:SHA,plan:planIssue({schema_version:1,mode:'MOCK',run_id:'run-1',observed_at:NOW,evidence:{repository:'fichil/fichil.com',slug:'demo',issues:{complete:true,slug:'demo',matches:created?[{number:1,slug:'demo',state:'open',created_at:NOW,confirmed_at:NOW}]:[]}}},NOW)});m.ports.invoke=async op=>{await invoke(op);created=true;};m.ports.reconcile=async op=>{if(++reads===2)throw Error('read outage');return read(op);};assert.equal((await createMutationDispatcher(m.ports,{execute:true}).dispatch({},identity)).status,'UNRESOLVED_STOP');assert.equal((await m.ports.prepare()).plan.intents[0].kind,'REUSE_UNIQUE_ISSUE');assert.equal((await createMutationDispatcher(m.ports,{execute:true}).recoverPending(identity)).status,'APPLIED_VERIFIED');assert.equal(m.calls.length,1);});
